### ISSUE TITLE
Не работает на экзешнике с исправленным разрешением.

### ISSUE THREAD

**Issue by Axe1s** [DaniilSokolyuk/CrimsonSkiesLauncher#1]
Вот [тут](https://community.pcgamingwiki.com/files/file/1425-crimson-skies-fix-for-widescreen-ultrawide-and-multi-mon/) взял патченные экзешники для разрешения 192х1080. С ним не запускается. Отдельно запускается. Может есть какой-то способ запустить с ключём и посмотреть почему не хочет?

**Comment by DaniilSokolyuk** [comment]
Привет! В readme инструкция, сейчас нормально работает только с помощью dgVoodoo2 wrapper, в той ссылке которую ты дал нужно взять v2_Crimson_Skies_dgV_Streched_HUD.7z или v2_Crimson_Skies_dgV.7z и следовать инструкции в Solution №1:

**Comment by Axe1s** [comment]
Во-первых спасибо  за твой труд!!!
Я прочёл инстукцию и всё получилось (использовал dgVoogoo2). НО!!!!! Разрешение растягивается от 4:3. И всё выглядит растянутым. А эти файлы реально дают нужное разрешение. Если будет возможность сделать альтернативу HUD, то было бы супер.
Ещё раз спасибо!!!

**Comment by DaniilSokolyuk** [comment]
Streched HUD растягивает интерфейс, а другой архив если взять интерфейс не должен растягиваться. Сама игра в обоих случаях не должна растягиваться

**Comment by Axe1s** [comment]
Всё!! Спасибо разобрался. Вопрос закрыт.
